ingress:
  hosts: []
  tls:
    enabled: false
    certManager:
      clusterIssuer: ""
      issuer: ""
  modsecurity:
    enabled: false
    owasp: false
    whitelist: ""
    restrictedUris: []
    restrictedWhitelist: ""
  nginx:
    configurationSnippet: ""
  annotations: ~

service:
  externalName: ""
  selector: ~
  ports:
    - port: 80
